attendance/urls.py
from django.urls import path
from django.conf import settings
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from rest_framework import permissions
from django.conf.urls.static import static
from .views import (
    home_view,
    login_view,
    logout_view,
    RegistrationWizardView,
    reset_new_password_view,
    add_worktime,
    get_worktime_details,
    update_worktime_by_kiosk_code,
    get_employees,
    get_worker_worktime,
    get_user_ids,
    add_subordinates,
    activate,
    get_employed_user_ids_json,
)
from .charts import template, line_chart_json
from .file_handlers import upload_file
from .worktime_report import WorktimeExportView,worktime_export
# router = DefaultRouter()
# router.register('data', RegistrationWizardView, basename='data')
# urlpatterns = router.urls
app_name = 'attendance'
schema_view = get_schema_view(
    openapi.Info(
        title="Attendance API",
        default_version='v1',),
    public=True,
    permission_classes=(permissions.AllowAny,),
)
urlpatterns = [
    path('', home_view, name='home'),
    path('login/', login_view, name='login'),
    path('change-password/', reset_new_password_view, name='reset_new_password_view'),
    path('worktime-by-kiosk-code/', update_worktime_by_kiosk_code, name='update_worktime_by_kiosk_code'),
    path('logout/', logout_view, name='logout'),
    path('register/', RegistrationWizardView.as_view(), name='register'),
    path('new-password/', reset_new_password_view, name='reset_new_password'),
    path('add-worktime/', add_worktime, name='add_worktime'),
    path('get-worktime-details/<int:entry_id>/', get_worktime_details, name='get_worktime_details'),
    path('get-worker-worktime/<int:user_id>/', get_worker_worktime, name='get_worker_worktime'),
    path('get-employees/', get_employees, name='get_employees'),
    path('add-subordinates/', add_subordinates, name='add_subordinates'),
    path('get-employees/<str:sort>/<str:filter>/', get_employees, name='get_employees'),
    path('docs/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('activate/<uidb64>/<token>', activate, name='activate'),
    path('charts', template, name='charts'),
    path('chartJSON', line_chart_json, name='line_chart_json'),
    path('get-user-ids/', get_user_ids, name='get_user_ids'),
    path('get-employed-user-ids/', get_employed_user_ids_json, name='get_employed_user_ids_json'),
    path('upload/', upload_file, name='upload_file'),
    path('report', WorktimeExportView.as_view(),name='report'),
    path('worktime-export/', worktime_export, name='worktime_export'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

core/urls.py
from django.urls import path, include
from .admin_site import admin_site

urlpatterns = [
    path('admin/', admin_site.urls),
    path('', include('attendance.urls', namespace="attendance")),
]

attendance/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, Group
from django.utils.translation import gettext_lazy as _
from django.dispatch import receiver
from django.db.models.signals import post_save


class CustomUser(AbstractUser):
    is_worker = models.BooleanField(default=False)
    is_company = models.BooleanField(default=False)
    is_manager = models.BooleanField(default=False)
    password_change_required = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        if self.is_worker:
            self.is_company = False
        elif self.is_company:
            self.is_worker = False
            self.is_manager = False
        super().save(*args, **kwargs)

class Company(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    name = models.TextField(_('name'), max_length=500, blank=True)
    address = models.TextField(_('address'), max_length=250, blank=True)

    def __str__(self):
        return f"{self.id} {self.user} {self.name} {self.address}"

class Worker(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    firstname = models.TextField(_('firstname'), max_length=500, blank=True)
    lastname = models.TextField(_('lastname'), max_length=255, blank=True)
    kiosk_code = models.CharField(_('kiosk_code'), max_length=10, blank=True)
    manager = models.ForeignKey('self', related_name='subordinate', on_delete=models.SET_NULL, blank=True, null=True)
    is_activated = models.BooleanField(default=False)

    def __str__(self):
        return f"""{self.id}. {self.firstname} {self.lastname}"""

class Worktime(models.Model):
    worker = models.ForeignKey(Worker, on_delete=models.CASCADE)
    date = models.DateField(auto_now_add=True, blank=True)
    punch_in = models.DateTimeField(blank=True)
    punch_out = models.DateTimeField(blank=True, null=True)
    total_time = models.DurationField(blank=True, null=True)

attendance/views.py
import json
from django.utils import timezone
import random
import string
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.contrib.auth.hashers import make_password
from django.http import JsonResponse
from django.utils.translation import gettext_lazy as _
from django.contrib import messages
from django.shortcuts import redirect, render
from django.contrib.auth.tokens import PasswordResetTokenGenerator
from django.template.loader import render_to_string
from django.contrib.sites.shortcuts import get_current_site
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_str
from django.core.mail import EmailMessage
from django.contrib.auth.decorators import login_required
from .forms import (
    CustomLoginForm,
    ChangePasswordForm,
    KioskCodeForm,
    RegisterCompanyForm,
    RegisterWorkerForm,
    RegistrationChoiceForm,
    AddSubordinateForm,
    CustomUserCreationForm
)
from .models import CustomUser, Worktime, Company, Worker
from .decorators import only_authenticated_user, redirect_authenticated_user
from django.shortcuts import get_object_or_404
from django.core.exceptions import ObjectDoesNotExist
from formtools.wizard.views import SessionWizardView
from rest_framework.decorators import api_view
from django.core.serializers import serialize
from django.db.models import Q
from datetime import timedelta
from django.conf import settings

EMAIL_ACTIVATION = getattr(settings, "EMAIL_ACTIVATION", True)

@only_authenticated_user
def home_view(request):
    print(request)
    user_id = request.user.id
    user = get_object_or_404(CustomUser, id=user_id)
    if user.is_worker:
        try:
            worker = Worker.objects.get(user_id=user_id)
        except ObjectDoesNotExist:
            return render(request, 'attendance/home.html', {'users': user, 'user_id': user_id,'error':'Worker not found'})
        worktime_entries = Worktime.objects.filter(worker=worker)
        return render(request, 'attendance/home.html',
                      {'users': user, 'user_id': user_id, 'worker': worker, 'worktime_entries': worktime_entries})
    if user.is_company:
        try:
            company = Company.objects.get(user_id=user_id)
        except ObjectDoesNotExist:
            return render(request, 'attendance/home.html', {'users': user,'error':'Company not found'})
        form = KioskCodeForm()
        return render(request, 'attendance/home.html', {'users': user, 'company': company, 'user_id': user_id, 'form': form})
    return redirect('attendance:logout')

@only_authenticated_user
def get_worker_worktime(request, user_id):
    requesting_user_id = request.user.id
    requesting_user = get_object_or_404(CustomUser, id=requesting_user_id)
    employed_users = [worker.user.id for worker in get_employed_worker_ids(request)]
    if user_id not in employed_users:
        return redirect('attendance:get_employees')
    try:
        worker = Worker.objects.get(user_id=user_id)
    except ObjectDoesNotExist:
        return render(request, 'attendance/employee_worktime.html', {'users': requesting_user, 'user_id': user_id})
    worktime_entries = Worktime.objects.filter(worker=worker)
    return render(request, 'attendance/employee_worktime.html', 
                  {'user': requesting_user, 'worker': worker, 'worktime_entries': worktime_entries})


def get_company_from_user(user_id):
    user = get_object_or_404(CustomUser, id=user_id)
    if not user.is_company:
        print("user is not company", user.is_company)
        return None
    return Company.objects.get(user_id=user_id)


def get_worker_from_user(user_id):
    user = get_object_or_404(CustomUser, id=user_id)
    if not user.is_worker:
        print("user is not worker", user.is_company)
        return None
    return Worker.objects.get(user_id=user_id)

def build_filter_q(request, filter_fields):
    filter_q = Q()
    filter_values = {}

    for field in filter_fields:
        filter_value = request.GET.get(field, '')
        lookup = 'exact' if field == 'user' else 'icontains'

        if filter_value:
            filter_q &= Q(**{f'{field}__{lookup}': filter_value})
        filter_values[field] = filter_value

    return filter_q, filter_values

@only_authenticated_user
def add_subordinates(request):
    if not request.user.is_manager:
        return redirect('attendance:home')
    manager = get_worker_from_user(request.user.id)
    if request.method == 'POST':
        form = AddSubordinateForm(request.POST,company=manager.company)
        if form.is_valid():
            subordinates = form.cleaned_data['subordinates']
            for subordinate in subordinates:
                subordinate.manager = manager
                subordinate.save()
            print("subordinates",subordinates)
            print("manager.subordinate.all()",manager.subordinate.all())
            print("Worker.objects.filter(manager=manager)",Worker.objects.filter(manager=manager))

            return redirect('attendance:home')
    else:
        form = AddSubordinateForm(company=manager.company)
    return render(request, 'attendance/add_subordinates.html', {'form': form, 'manager': manager})

@only_authenticated_user
def get_employees(request, sort='user_id', filter=''):
    company = get_company_from_user(request.user.id)
    if not company and not request.user.is_manager:
        return JsonResponse({'error': 'User is not associated with a company'})
    sort_param = request.GET.get('sort', 'user_id')
    filter_fields = ['user', 'firstname', 'lastname', 'kiosk_code']
    filter_q, filter_values = build_filter_q(request, filter_fields)
    if company:
        combined_filter = Q(company=company) & filter_q
    if request.user.is_manager:
        manager = get_worker_from_user(request.user.id)
        combined_filter = Q(company=manager.company) & Q(manager=manager) & filter_q
    workers = json.loads(serialize("json", Worker.objects.filter(combined_filter).order_by(sort_param)))
    if 'clear_filters' in request.GET:
        return redirect('attendance:get_employees')

    context = {
        'workers': workers,
        'current_sort': sort_param,
        'filter_values': filter_values.items(),
        'filter_fields': filter_fields,
        'company': company
    }

    return render(request, 'attendance/employees.html', context)

def get_user_ids(request):
    workers = Worker.objects.all().values('user_id', 'firstname','lastname')
    print(workers)
    return JsonResponse({'workers': list(workers)})

def get_employed_user_ids_json(request):
    
    company = get_company_from_user(request.user.id)
    if company:
        print("company",company)
        workers = Worker.objects.all().values('user_id', 'firstname','lastname')
    if request.user.is_manager:
        manager = get_worker_from_user(request.user.id)
        print("manager",manager)
        workers = Worker.objects.filter(manager=manager).values('user_id', 'firstname','lastname')
    print(workers)
    return JsonResponse({'workers': list(workers)})

def get_employed_worker_ids(request):
    company = get_company_from_user(request.user.id)
    if company:
        workers = Worker.objects.filter(company=company)
    if request.user.is_manager:
        manager = get_worker_from_user(request.user.id)
        workers = Worker.objects.filter(manager=manager)
    if request.user.is_worker and not request.user.is_manager:
        workers = [get_worker_from_user(request.user.id)]
    return workers

@login_required
@api_view(['POST'])
def add_worktime(request, worker=None):
    print("adding worktime")
    if request.method == 'POST':
        user_id = request.POST.get('user_id')
        if worker is None:
            worker = get_worker_from_user(user_id)
        existing_entry = Worktime.objects.filter(worker=worker, punch_out__isnull=True).first()
        if existing_entry:
            existing_entry.punch_out = timezone.now()
            existing_entry.total_time = existing_entry.punch_out - existing_entry.punch_in
            existing_entry.total_time = timedelta(seconds=round(existing_entry.total_time.total_seconds()))
            existing_entry.save()
            return JsonResponse({'status': 'success'})
        new_entry = Worktime(worker=worker, punch_in=timezone.now(), date=timezone.now().date())
        new_entry.save()
        return JsonResponse({'status': 'success', 'entry_id': new_entry.id})


@api_view(['GET'])
def get_worktime_details(request,entry_id):
    worktime = get_object_or_404(Worktime, id=entry_id)
    data = {
        'date': worktime.date,
        'punch_in': worktime.punch_in,
        'punch_out': worktime.punch_out,
        'total_time': worktime.total_time,
    }
    return JsonResponse(data)


@login_required
def update_worktime_by_kiosk_code(request):
    print("Updating worktime by kiosk code")
    if request.method == 'POST':
        user_id = request.POST.get('user_id')
        form = KioskCodeForm(request.POST)
        if form.is_valid():
            company = Company.objects.get(user_id=user_id)
            kiosk_code = form.cleaned_data['kiosk_code']
            try:
                worker = Worker.objects.get(company=company, kiosk_code=kiosk_code)
            except ObjectDoesNotExist:
                return JsonResponse({'status': 'failure', 'message': "Worker with that Kiosk Code was not found."})
            response = add_worktime(request, worker)
            response_data = response.content.decode("UTF-8")
            worker_info = f"{worker.firstname} {worker.lastname}"
            if 'entry_id' in response_data:
                return JsonResponse({'status': 'success', 'message':
                                     "Successfully created a new worktime entry for: ", 'worker': worker_info})
            return JsonResponse({'status': 'success', 'message':

attendance/templates/attendance/add_subordinates.html
{% extends 'shared_layout/base.html' %}

{%block contents%}




{% if user.is_company == 1 or user.is_manager%}
<p><strong>User ID:</strong> {{ user.id }}</p>
<p><strong>Email:</strong> {{ user.email }}</p>
<h1>Add Subordinates for Manager: {{ manager.firstname }} {{ manager.lastname }}</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Add Subordinates</button>
    </form>
{% endif %}


{%endblock contents%}

attendance/templates/attendance/charts.html
{% extends 'shared_layout/base.html' %}

{%block contents%}




{% load static %}
{% if user.is_company == 1 or user.is_manager%}
<h2>{{ company.name }} Company Profile </h2>
<p><strong>User ID:</strong> {{ user.id }}</p>
<p><strong>Email:</strong> {{ user.email }}</p>
<h1>Total worktime of worker: </h1>


<select id="user_id_dropdown"></select>
<div class="chartCard">
    <div class="chartBox">
        <div class="containerBody">
            <div class="colSmall">
                <canvas id="myChart2"></canvas>
            </div>
            <div class="colLarge">
                <div class="box">
                    <canvas id="myChart"></canvas>
                </div>
            </div>
        </div>
    </div>
</div>
        <script type="text/javascript" src="http://code.jquery.com/jquery-1.10.0.min.js"></script>
        <script type="text/javascript" src="{% static 'js/Chart.min.js' %}"></script>
        <script type="text/javascript">
            Chart.defaults.global.legend.display = false;
            $(document).ready(function() {
                var myChart;
                var myChart2;
                function fetchChartData(userId) {
                    
                    var chartUrl = '{% url "attendance:line_chart_json" %}?user_id=' + userId;
                    $.get(chartUrl, function(data) {
                        if (myChart) {
                            myChart.destroy();
                                    }
                        if (myChart2) {
                            myChart2.destroy();
                                    }
                        var ctx = $("#myChart").get(0).getContext("2d");
                        var ctx2 = $("#myChart2").get(0).getContext("2d");
                        
                
                        
            var config = {
                type: 'bar', 
                data: data,
                options: {
                    maintainAspectRatio: false,
                    layout:{
                        padding:{
                            top: 20,
                        },
                    },
                    scales: {
                        yAxes: [{
                            beginAtZero: true,
                            ticks: {
                                display: false, 
                                    },
                            grid: [{
                                drawTicks: false,
                                drawBorder: false,
                            }],
                                },]
                        
                            },
                }
            }
            var config2 = {
                type: 'bar', 
                data: data,
                options: {
                    maintainAspectRatio: false,
                    layout:{
                        padding:{
                            top: 20,
                            bottom: 38,
                        },
                    },
                    scales: {
                        xAxes:[{
                            display:false,
                            ticks: {
                                display: false, 
                                    },
                            grid: {
                                drawTicks: false,
                            },
                        },],
                        yAxes: [{
                                beginAtZero: true,
                                afterFit:(ctx2) => {
                                    console.log(ctx2);
                                    ctx2.width = 40;
                                }
                                }]
                            },
                        }
            }
                        myChart = new Chart(ctx,config );
                        myChart2 = new Chart(ctx2,config2 );
            console.log("myChart");
            console.log(myChart);
            console.log(myChart2);
        
            const box = document.querySelector('.box');
            const totalLabels = myChart.data.labels.length
            if(totalLabels > 25){
                console.log("over 25");
                const newWidth = 900 + ((totalLabels - 25) * 36)
                box.style.width = `${newWidth}px`
            }
        });
    }
        
                // Populate dropdown with worker information
    var dropdown = $('#user_id_dropdown');
    dropdown.empty();
    dropdown.append('<option selected="true" disabled>Select Person</option>');
    dropdown.prop('selectedIndex', 0);
    var url = '{% url "attendance:get_employed_user_ids_json" %}';
    $.getJSON(url, function(data) {
        $.each(data.workers, function(key, worker) {
            var optionText = worker.firstname && worker.lastname ? worker.firstname + ' ' + worker.lastname : 'ID: ' + worker.user_id;
            optionText += ' (ID: ' + worker.user_id + ')';
            dropdown.append($('<option></option>').attr('value', worker.user_id).text(optionText));
        });
    }).fail(function() {
        console.error('Failed to fetch worker information.');
    });

    dropdown.on('change', function() {
        var userId = $(this).val();
        fetchChartData(userId);
        var selectedWorkerText = $('option:selected', this).text();
        $('h1').text('Total worktime of worker: ' + selectedWorkerText);
        
    });
});
        </script>
        
{% endif %}


{%endblock contents%}

attendance/templates/attendance/employees.html
{% extends 'shared_layout/base.html' %}

{%block contents%}




{% if user.is_company == 1 or user.is_manager%}
<p><strong>User ID:</strong> {{ user.id }}</p>
<p><strong>Email:</strong> {{ user.email }}</p>
{{error}}
<div id="employees_table_container">
    <table id="employees_table">
        <form method="get" action="{% url 'attendance:get_employees' %}">
            {% for field, filter_value in filter_values %}
            <th><input type="text" name="{{ field }}" placeholder="Filter by {{ field.capitalize }}" value="{{ filter_value }}"></th>
            {% endfor %}
            <button type="submit">Apply Filter</button>
            <button type="submit" name="clear_filters">Clear Filters</button>
        </form>
        <thead>
            <tr>
                {% for field, filter_value in filter_values %}
                <th>
                    
                    <a href="?sort={{ field }}{% for f, v in filter_values %}&{{ f }}={{ v }}{% endfor %}">
                        {{ field.capitalize }}
                      </a>
                </th>
                {% endfor %}
        </thead>
        <tbody>
            {% for worker in workers %}
                <tr>
                    <td><a href="{% url 'attendance:get_worker_worktime'  worker.fields.user  %}">{{ worker.fields.user }}</a></td>
                    <td>{{ worker.fields.firstname }}</td>
                    <td>{{ worker.fields.lastname }}</td>
                    <td>{{ worker.fields.kiosk_code }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% endif %}


{%endblock contents%}

attendance/templates/attendance/file_upload.html
<!DOCTYPE html>
{% extends 'shared_layout/base.html' %}

{%block title%}
file upload
{%endblock title%}

{%block contents%}
{%if error%}
<div class="alert alert-danger" role="alert">
    {{error}}
</div>
{%endif%}
{% if message %}
    <p>{{ message }}</p>
{% endif %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="file" name="file" accept=".csv, .json, .xlsx">
    <button type="submit">Upload File</button>
</form>

{%endblock contents%}

attendance/templates/attendance/home.html
{% extends 'shared_layout/base.html' %}

{%block contents%}

{% if user.is_company == 0 and  user.is_worker == 1 or user.is_manager == 1%}

<h2>Username: {{ user.username }}</h2>
{% if worker %}
<h2>Employed by: {{ worker.company.name }}</h2>
<h2>Kiosk Code: {{ worker.kiosk_code }}</h2>
<h2>Firstname: {{ worker.firstname }}</h2>
<h2>Lastname: {{ worker.lastname }}</h2>
{% endif %}
<h2>{{error}} </h2>
{% if worktime_entries %}
<h2>Worktime Entries:</h2>


<div id="worktime_table_container">
    <table id="worktime_table">
        <thead>
            <tr>
                <th>Date:</th>
                <th>Punch In:</th>
                <th>Punch Out:</th>
                <th>Total Time:</th>
            </tr>
        </thead>
        <tbody>
            {% for entry in worktime_entries %}
                <tr>
                    <td>{{ entry.date }}</td>
                    <td>{{ entry.punch_in }}</td>
                    <td>{{ entry.punch_out }}</td>
                    <td>{{ entry.total_time}}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

<script>
    // Scroll to the bottom of the table container
    var container = document.getElementById('worktime_table_container');
    container.scrollTop = container.scrollHeight;
</script>

{% else %}
    <p>No worktime entries available.</p>
{% endif %}
<div class="align-right">
    <button id="updateWorktimeButton">Update Worktime</button>
</div>
{% endif %}

<script>
    $(document).ready(function() {
        $('#updateWorktimeButton').on('click', function() {
            const csrftoken = Cookies.get('csrftoken');
            $.ajax({
                type: 'POST',
                url: '{% url "attendance:add_worktime" %}',
                data: {
                    user_id: '{{ user.id }}',
                    'csrfmiddlewaretoken': csrftoken
                },
                dataType: 'json',
                success: function (data) {
                    if (data.status === 'success') {
                        location.reload();
                    } else {
                    }
                },
                error: function () {
                }
            });
        });
    });
    </script>

{% if user.is_company == 1 and user.is_worker == 0%}
{% if company%}
<h2>{{ company.name }} Company Profile </h2>
{% endif %}
<h2>{{error}} </h2>
<p><strong>User ID:</strong> {{ user.id }}</p>
<p><strong>Email:</strong> {{ user.email }}</p>


<form id='kiosk_code_form' method="post">
    {%csrf_token%} {%include 'attendance/form_snippets.html' with form=form%}
    <input id='kiosk_code' class="btn btn-primary" type="submit" value="Update Worktime">
    <div id="alert"></div>
</form>
{% endif %}

<div id="alert"></div>
<script>
    $(document).ready(function() {
        $('#kiosk_code_form').on('submit', function() {
            event.preventDefault();
            
            const csrftoken = Cookies.get('csrftoken');
            $.ajax({
                type: 'POST',
                url: '{% url "attendance:update_worktime_by_kiosk_code" %}',  // Replace with the actual URL name of your update_worktime view
                data: {
                    kiosk_code: $('#kiosk_code_').val(),
                    user_id: '{{ user.id }}',  // Replace with the actual user ID or how you obtain it in your context
                    'csrfmiddlewaretoken': csrftoken
                },
                dataType: 'json',
                
                success: function (data) {
                    
                    if (data.status === 'success') {
                        // Optional: Display a success message or perform other actions
                        //$('#kiosk_code_form').hide();
                        //$('#kiosk_code_form').val('');
                        //$('#kiosk_code_form')[0].reset();
                        document.getElementById("kiosk_code_form").reset();
                        $('#alert').html('<div class="alert alert-success">'  + data.message + data.worker + '</div>').show();
                        console.log(data);
                        console.log(data.message);
                        //$('#alert').html('<div class="alert alert-success">' + response.message + '</div>').show();
                        //location.reload();
                        // Assuming you have an HTML element with the ID 'worktime_table'

                        // Update the table with the new entry
                    } else {
                        $('#alert').html('<div class="alert alert-warning">'  + data.message +  '</div>').show();
                        // Handle errors if needed
                    }
                },
                error: function () {
                    // Handle errors if needed
                }
            });
        });
    });
    </script>
{%endblock contents%}

attendance/templates/attendance/invalid_token.html
{% extends 'shared_layout/base.html' %}

{%block contents%}




<h1>This link is invalid</h1>
    



{%endblock contents%}

attendance/templates/attendance/login.html
<!DOCTYPE html>
{% extends 'shared_layout/base.html' %}

{%block title%}
login
{%endblock title%}

{%block contents%}
{%if error%}
<div class="alert alert-danger" role="alert">
    {{error}}
</div>
{%endif%}
{%if data.message%}
<div class="alert alert-danger" role="alert">
    {{data.message}}
</div>
{%endif%}
{%if message%}
<div class="alert alert-danger" role="alert">
    {{message}}
</div>
{%endif%}
<form method="post">
    {%csrf_token%}
    {%include 'attendance/form_snippets.html' with form=form%}                
    <input class="btn btn-primary" type="submit" value="Login">
</form>


<div class="my-2">
    <small class="text-muted">
        Need an account ? <a class="ml-2" href="{%url 'attendance:register'%}">Sign Up</a>
    </small>
</div>
<div class="my-2">
    <small class="text-muted">
        Need to change password ? <a class="ml-2" href="{%url 'attendance:reset_new_password_view'%}">Change password</a>
    </small>
</div>
{%endblock contents%}

attendance/templates/attendance/register.html
<!DOCTYPE html> {% extends 'shared_layout/base.html' %} {%block title%} register {%endblock title%} {%block contents%} {%if error%}
<div class="alert alert-danger" role="alert">
    {{error}}
</div>
{%endif%}
<form method="post">
    {%csrf_token%} {%include 'attendance/form_snippets.html' with form=form%}
    <input class="btn btn-primary" type="submit" value="Register">
</form>


<div class="my-2">
    <small class="text-muted">
        Already have an account ? <a class="ml-2" href="{%url 'attendance:login'%}">Sign In</a>
    </small>
</div>
{%endblock contents%}

attendance/templates/attendance/wizard_form.html
<!DOCTYPE html> {% extends 'shared_layout/base.html' %} {%block title%} register {%endblock title%} {%block contents%} {%if error%}
<div class="alert alert-danger" role="alert">
    {{error}}
</div>
{%endif%}
<form method="post">
    {%csrf_token%}{{ wizard.management_form }} {%include 'attendance/form_snippets.html' with form=form%}
    <input class="btn btn-primary" type="submit" value="Register">
</form>

<small class="text-muted">
    Already have an account ? <a class="ml-2" href="{%url 'attendance:login'%}">Sign In</a>
</small>
{% endblock %}

attendance/templates/attendance/worktime_export.html
<!DOCTYPE html>
{% extends 'shared_layout/base.html' %}

{% block title %}
file upload
{% endblock title %}

{% block contents %}
{% if error %}
<div class="alert alert-danger" role="alert">
    {{ error }}
</div>
{% endif %}
<form id="worktimeForm" method="GET" action="{% url 'attendance:worktime_export' %}">
    <label for="year">Select Year:</label>
    <select name="year" id="year">
        {% for year in years %}
        <option value="{{ year }}">{{ year }}</option>
        {% endfor %}
    </select>
    <label for="month">Select Month:</label>
    <select name="month" id="month">
        {% for month_num, month_name in months.items %}
        <option value="{{ month_num }}">{{ month_name }}</option>
        {% endfor %}
    </select>
    <label for="worker">Select Worker:</label>
    <select name="worker" id="worker">
        <option value="">All</option>
        {% for worker in workers %}
        <option value="{{ worker }}">{{ worker }}</option>
        {% endfor %}
    </select>
    <button type="submit">Export</button>
</form>
{% if worktime_entries %}
<p>{{ worktime_entries }}</p>
{% endif %}

{% endblock contents %}