attendance/urls.py
from django.urls import path
from django.conf import settings
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from rest_framework import permissions
from django.conf.urls.static import static
from .views import (
    home_view,
    login_view,
    logout_view,
    RegistrationWizardView,
    reset_new_password_view,
    add_worktime,
    get_worktime_details,
    update_worktime_by_kiosk_code,
    get_employees,
    get_worker_worktime,
    get_user_ids,
    add_subordinates,
    activate,
    get_employed_user_ids_json,
)
from .charts import template, line_chart_json
from .file_handlers import upload_file
from .worktime_report import WorktimeExportView,worktime_export
# router = DefaultRouter()
# router.register('data', RegistrationWizardView, basename='data')
# urlpatterns = router.urls
app_name = 'attendance'
schema_view = get_schema_view(
    openapi.Info(
        title="Attendance API",
        default_version='v1',),
    public=True,
    permission_classes=(permissions.AllowAny,),
)
urlpatterns = [
    path('', home_view, name='home'),
    path('login/', login_view, name='login'),
    path('change-password/', reset_new_password_view, name='reset_new_password_view'),
    path('worktime-by-kiosk-code/', update_worktime_by_kiosk_code, name='update_worktime_by_kiosk_code'),
    path('logout/', logout_view, name='logout'),
    path('register/', RegistrationWizardView.as_view(), name='register'),
    path('new-password/', reset_new_password_view, name='reset_new_password'),
    path('add-worktime/', add_worktime, name='add_worktime'),
    path('get-worktime-details/<int:entry_id>/', get_worktime_details, name='get_worktime_details'),
    path('get-worker-worktime/<int:user_id>/', get_worker_worktime, name='get_worker_worktime'),
    path('get-employees/', get_employees, name='get_employees'),
    path('add-subordinates/', add_subordinates, name='add_subordinates'),
    path('get-employees/<str:sort>/<str:filter>/', get_employees, name='get_employees'),
    path('docs/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('activate/<uidb64>/<token>', activate, name='activate'),
    path('charts', template, name='charts'),
    path('chartJSON', line_chart_json, name='line_chart_json'),
    path('get-user-ids/', get_user_ids, name='get_user_ids'),
    path('get-employed-user-ids/', get_employed_user_ids_json, name='get_employed_user_ids_json'),
    path('upload/', upload_file, name='upload_file'),
    path('report', WorktimeExportView.as_view(),name='report'),
    path('worktime-export/', worktime_export, name='worktime_export'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

core/urls.py
from django.urls import path, include
from .admin_site import admin_site

urlpatterns = [
    path('admin/', admin_site.urls),
    path('', include('attendance.urls', namespace="attendance")),
]

templates/shared_layout/base.html
<!DOCTYPE html>

<html lang="en">
    
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
    <script src="https://code.jquery.com/jquery-migrate-3.3.2.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/js-cookie/3.0.1/js.cookie.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <title>{%block title%}{%endblock title%}</title>
    {%block customcss%}
    <style>
        #worktime_table_container, #employees_table_container  {
        overflow-y: auto;
         
    }
    #worktime_table_container{
        max-height: 300px;
    }
    #employees_table_container  {
        max-height: 600px;
    }

    #worktime_table, #employees_table {
        width: 100%;
        border-collapse:separate;
        border:solid white 1px;
        border-radius:6px;
    }
    
    #worktime_table th, #employees_table th, #worktime_table td, #employees_table td {
        padding: 8px;
        text-align: center;
    }
        
    html, body {
    margin: 0;
    height: 100%;
    min-height: 100%;
    overflow: auto;
    }
    #worktime_table th, #employees_table th{
        background-color: #39445a;
    }
    tr:nth-child(even) {
            background-color: #39445a;
        }
    tr:nth-child(odd) {
            background-color: #232a38;
        }
    tr:last-child {
            font-weight: bold;
        }
    #updateWorktimeButton{
        text-align: right;
        margin-top: 10px;
    }
    #alert{
        margin-top: 10px;
        width: fit-content;
    }
    #kiosk_code{
        margin-top: 10px;
        width: fit-content;
    }
    .align-right {
        text-align: right;
      }
    #container{
    /*background: transparent linear-gradient(180deg, #FFE5EC 0%, #9796F0 100%) 0% 0% no-repeat ;*/
    background: #181d27;
    text-align: left;
    color: white;
    }
    #nav-item{
        color: white !important;
    }
    
    a:link,a:visited{
        color: white;
    }
    .chartCard {
    width: 100%;
    overflow: hidden; /* Hide the scrollbar by default */
    position: relative; /* Position context for absolutely positioned elements */
    
}

.chartBox {
    width: 900px;
    padding: 20px;
    border-radius: 20px;
    border: solid 3px rgba(54, 162, 235, 1);
    background: white;
    
}

.containerBody {
    height: 600px;
    /*display: inline-block;  Ensure the container respects its width */
    position: relative; /* Position context for absolutely positioned elements */
    display: flex;
}


.colSmall{
    width: 30px;
    height: 500px;
}
.colLarge{
    max-width: 900px;
    overflow-x: scroll;
}
.box{
    width: calc(900px - 35px);
    height: 500px;
}
button,select{
    border-radius: 8px;
}

.nav-link{
    color: white !important;
}

    
</style>
{%endblock customcss%}
</head>
<body id="container">
    {%include 'shared_layout/navbar.html'%}
    <div class="container my-3">
        {% if messages %}
        {% for message in messages %}
        
        {% endfor %}
        {% endif %}

        {%block contents%}
        {%endblock contents%}
    </div>
    
    {%block customjs%}
    {%endblock customjs%}
</body>
</html>

templates/shared_layout/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark px-2">
    <a class="navbar-brand" href="{%url 'attendance:home'%}">ATTENDANCE</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        {%if user.is_authenticated%}
        <li class="nav-item">
            <a class="nav-link" href="{%url 'attendance:home'%}">Home</a>
        </li>
        
        {%endif%}
        {%if user.is_company and user.is_authenticated%}
        <li class="nav-item">
            <a class="nav-link" href="{%url 'attendance:get_employees'%}">Employees</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{%url 'attendance:charts'%}">Charts</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{%url 'attendance:upload_file'%}">Create Accounts</a>
        </li>
        {%endif%}
        {%if user.is_manager and user.is_authenticated%}
        <li class="nav-item">
            <a class="nav-link" href="{%url 'attendance:get_employees'%}">Employees</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{%url 'attendance:charts'%}">Charts</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{%url 'attendance:add_subordinates'%}">Add Subordinates</a>
      </li>
        {%endif%}
        {%if user.is_authenticated%}
        <li class="nav-item">
          <a class="nav-link" href="{%url 'attendance:worktime_export'%}">Worktime Export</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{%url 'attendance:logout'%}">Logout</a>
        </li>
        
        {%else%}
        <li class="nav-item">
            <a class="nav-link" href="{%url 'attendance:login'%}">Login</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{%url 'attendance:register'%}">register</a>
        </li>
        {%endif%}
      </ul>
    </div>
  </nav>